# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=800)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=10)),
                ('fees', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.CreateModel(
            name='CreatedEvents',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.Event')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.UserInfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('event_type', 'location', 'date_time')]),
        ),
    ]
