# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=800)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
