# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_auto_20190324_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startdate',
        ),
    ]
