# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_auto_20190427_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
