# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_auto_20190324_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='state',
        ),
    ]
