# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_auto_20190427_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdevents',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.Event', unique=True),
        ),
    ]
