# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_remove_userinfo_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='user_name',
        ),
    ]
