# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_auto_20190427_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdevents',
            name='event_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='event_management.Event', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createdevents',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
