# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_auto_20190427_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdevents',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.Event'),
        ),
    ]
