# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_auto_20190412_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
