# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0006_auto_20190421_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventdate',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventname',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='events_created',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='events_interested',
            field=models.TextField(null=True),
        ),
    ]
