# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_auto_20190507_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([]),
        ),
    ]
