# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_auto_20190421_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('event_type', 'location', 'date_time')]),
        ),
    ]
